### ISSUE TITLE
assertion error on PG11

### ISSUE THREAD

**Issue by gsmolk** [petergeoghegan/amcheck#18] opened 2019-10-08 08:50 UTC
Hello!
I`ve encountered the subj on freshly inited database. Steps to reproduce:
```
postgres=# select version();
                                                version                                                 
--------------------------------------------------------------------------------------------------------
 PostgreSQL 11.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 9.2.1 20190827 (Red Hat 9.2.1-1), 64-bit
(1 row)

[#]$ pgbench -i -s 5 postgres
dropping old tables...
NOTICE:  table "pgbench_accounts" does not exist, skipping
NOTICE:  table "pgbench_branches" does not exist, skipping
NOTICE:  table "pgbench_history" does not exist, skipping
NOTICE:  table "pgbench_tellers" does not exist, skipping
creating tables...
generating data...
100000 of 500000 tuples (20%) done (elapsed 0.13 s, remaining 0.54 s)
200000 of 500000 tuples (40%) done (elapsed 0.27 s, remaining 0.40 s)
300000 of 500000 tuples (60%) done (elapsed 0.44 s, remaining 0.30 s)
400000 of 500000 tuples (80%) done (elapsed 0.57 s, remaining 0.14 s)
500000 of 500000 tuples (100%) done (elapsed 0.72 s, remaining 0.00 s)
vacuuming...
creating primary keys...
done.

postgres=# create extension amcheck_next ;
CREATE EXTENSION
postgres=# SELECT public.bt_index_check('pgbench_accounts_pkey', false);
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.


TRAP: FailedAssertion("!(((_Bool) (((const void*)(&(itup->t_tid)) != ((void *)0)) && ((&(itup->t_tid))->ip_posid != 0))))", File: "verify_nbtree.c", Line: 667)
2019-10-07 21:14:25 GMT [23592]: [9-1] LOG:  server process (PID 23898) was terminated by signal 6: Aborted
2019-10-07 21:14:25 GMT [23592]: [10-1] DETAIL:  Failed process was running: SELECT public.bt_index_check('pgbench_accounts_pkey', false);
```

**Comment by petergeoghegan** [comment] 2019-10-08 15:57
This is harmless. It's caused by our use of ItemPointerGetBlockNumber() rather than ItemPointerGetBlockNumberNoCheck(). On v11 code is supposed to use BTreeInnerTupleGetDownLink(), which is a simple wrapper for ItemPointerGetBlockNumberNoCheck(), because the INCLUDE indexes feature truncates "negative infinity" items on internal pages to 0 columns explicitly (i.e. the offset number field is 0, which is wrong in general by correct with the type punning used in nbtree from v11 on).

I'll push a fix, but there is nothing to worry about here.

**Comment by petergeoghegan** [comment] 2019-10-08 15:58
(I realize that you're not using an INCLUDE index here -- I meant that the INCLUDE index feature established that general convention for all B-Tree indexes)

**Comment by petergeoghegan** [comment] 2019-10-08 16:07
Note also that Postgres v11 isn't supported by amcheck_next -- you should really be using contrib/amcheck there, which has all the same functionality.

I've pushed a fix all the same.

Thanks

**Closed as completed by petergeoghegan** 2019-10-08 16:07 UTC

**Comment by gsmolk** [comment] 2019-10-08 16:16
Thank you!

**Comment by petergeoghegan** [comment] 2019-10-08 16:19
@gsmol Actually, I had to revert that -- the macros don't appear until Postgres 10, and I'm not willing to add a bunch of ifdef cruft to make everything work.

You can either build without that revert commit, or use contrib/amcheck from v11. I strongly recommend the latter, though.

**Comment by gsmolk** [comment] 2019-10-08 18:54
Ok, thanks all the same!
